
export const COMMAND_CATEGORIES: Record<string, string[]> = {
    '设备基础信息巡检': [
        'display version', 
        'display startup',
        'display license',
        'display patch-information',
        'display clock',
        'dir flash:',
        'display current-configuration',
        'display debugging',
        'compare configuration',
    ],
    '设备运行情况巡检': [
        'display device',
        'display fan',
        'display power',
        'display alarm',
        'display cpu-usage',
        'display memory',
        'display logbuffer',
        'display ftp-server',
        'display device temperature',
    ],
    '端口内容巡检': [
        'display interface',
        'display current-configuration interface',
        'display interface brief',
        'display ip interface',
    ],
    '业务运行巡检': [
        'display igmp-snooping port-info',
        'display igmp-snooping statistics vlan',
        'display l2-multicast forwarding-table',
        'display multicast forwarding-table',
        'display multicast routing-table',
        'display dhcp snooping user-bind all',
        'display mac-address',
        'display ip routing-table',
        'display ospf error',
        'display vrrp',
        'display vrrp statistics',
        'display current-configuration | include car',
        'display stp brief',
        'display stp region-configuration',
        'display stp topology-change',
        'display stp tc-bpdu statistics',
        'display loop-detection',
        'display ospf peer',
        'display ospf peer last-nbr-down',
        'display isis peer',
        'display bgp peer',
        'display current-configuration configuration ospf',
        'display router id',
        'display ospf vlink',
        'display current-configuration configuration isis',
        'display current-configuration configuration bgp',
        'display vlan',
        'reset cpu-defend statistics all',
        'display cpu-defend statistics all'
    ]
};

export const categories = Object.keys(COMMAND_CATEGORIES);
